pipeline {
    agent any

    stages {
        stage ('Clean WS') {
            steps{
                cleanWs()
            }
        }

        stage ('pull repo with site') {
            steps{
                git branch: 'main', url: 'https://github.com/devopsfabric/single-page.git'
            }
        }
    }

    
}