pipeline {
    agent any
    environment {
        BUCKET_NAME = "fabrika-terraform-site"
        ENDPOINT_URL = "https://storage.yandexcloud.net"
        }
    stages {
        stage ('Clean WS') {
            steps{
                cleanWs()
            }
        }

        stage ('pull repo with site') {
            steps{
                git branch: 'main', url: 'https://github.com/devopsfabric/single-page.git'
            }
        }

        stage ('copy to s3') {
            steps{
                withAWS(credentials: 's3-editor', endpointUrl: "${ENDPOINT_URL}", region: 'ru-central1-a') {
                    s3Delete bucket: "${BUCKET_NAME}", path: '/'
                    s3Upload acl: 'Private', bucket: "${BUCKET_NAME}", includePathPattern: '**/*'
                    }
            }
        }
    }
}