pipeline {
    agent any

    stages {
        stage ('Clean WS') {
            steps{
                cleanWs()
            }
        }

        stage ('pull repo with site') {
            steps{
                git branch: 'main', url: 'https://github.com/devopsfabric/single-page.git'
            }
        }

        stage ('copy to s3') {
            steps{
                withAWS(credentials: 's3-editor', endpointUrl: 'https://storage.yandexcloud.net', region: 'ru-central1-a') {
                    s3Upload acl: 'Private', bucket: 'fabrika-terraform-site', includePathPattern: '**/*'
                    }
            }
        }
    }

    
}