services:
  vault:
    container_name: vault
    image: hashicorp/vault
    restart: always
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault.json:/vault/config/vault.json
      - vault-data:/vault/file:rw
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json

volumes:
  vault-data: